supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
allowBuilds:
  bcrypt: true
  core-js: set this to true or false
  esbuild: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
