-- ============================================================
-- Hub Inspections — Migracion 18: Importacion de Siniestros
-- OBSOLETA: La importacion se realiza via script JS para homologacion inteligente
-- Los datos se importan con scripts/final_import_claims.js
-- ============================================================
