-- ═══════════════════════════════════════════════════════════════
-- Migración 238: Tipos de Bien + Productos + Marcas
-- ═══════════════════════════════════════════════════════════════
--
-- Estructura jerárquica para daños de contenido:
--   content_good_types   (Tipos de Bien — raíz, ej: Electrodomésticos)
--     └── content_good_products (Productos — hoja, ej: Refrigerador)
--   content_good_brands  (Marcas — catálogo global, ej: Samsung)
--
-- Modelo:
--   - Marca es GLOBAL (no se duplica). Samsung existe 1 vez.
--   - Producto es genérico (sin marca). "Lavadora" existe 1 vez.
--   - En inspection_damages, el inspector combina:
--       product_id (FK a content_good_products)
--       brand_id   (FK a content_good_brands)
--     Así "Lavadora Samsung" y "Lavadora LG" son el mismo producto
--     con distinta marca, sin duplicar el catálogo.
--
-- Cambios sobre content_good_types existentes (migración 159):
--   - Renombramientos (UPDATE, no toca IDs ni datos):
--       Maquinaria           → Maquinaria y Herramientas
--       Enseres Generales    → Enseres de Cocina
--       Móviles              → Computación y Móviles
--       Electrónica          → (mismo nombre, descripción afinada)
--       Joyas / Bisutería    → (mismo nombre, descripción afinada)
--   - 4 tipos nuevos (INSERT):
--       Alimentos / Víveres
--       Jardinería / Exterior
--       Seguridad / Smart Home
--       Óptica / Astronomía
--
-- Cambios sobre inspection_damages:
--   - ADD COLUMN product_id (FK a content_good_products, nullable)
--   - ADD COLUMN brand_id   (FK a content_good_brands, nullable)
--   Las columnas product/brand_model (TEXT libres) se conservan.
-- ═══════════════════════════════════════════════════════════════

-- ── 1. content_good_brands (Marcas — catálogo global) ──
CREATE TABLE IF NOT EXISTS content_good_brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  country TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE content_good_brands ENABLE ROW LEVEL SECURITY;
CREATE POLICY "content_good_brands_select" ON content_good_brands FOR SELECT USING (true);
CREATE POLICY "content_good_brands_all" ON content_good_brands FOR ALL USING (true) WITH CHECK (true);

-- ── 2. content_good_products (Productos — hoja de tipos de bien) ──
CREATE TABLE IF NOT EXISTS content_good_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_good_type_id UUID NOT NULL REFERENCES content_good_types(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE content_good_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "content_good_products_select" ON content_good_products FOR SELECT USING (true);
CREATE POLICY "content_good_products_all" ON content_good_products FOR ALL USING (true) WITH CHECK (true);

-- Índice para filtrar productos por tipo
CREATE INDEX IF NOT EXISTS idx_content_good_products_type_id ON content_good_products(content_good_type_id);
CREATE INDEX IF NOT EXISTS idx_content_good_products_active ON content_good_products(is_active);

-- ── 3. inspection_damages: agregar product_id y brand_id ──
ALTER TABLE inspection_damages
  ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES content_good_products(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS brand_id UUID REFERENCES content_good_brands(id) ON DELETE SET NULL;

COMMENT ON COLUMN inspection_damages.product_id IS 'Producto del catálogo (FK a content_good_products). Nullable para compatibilidad con datos existentes.';
COMMENT ON COLUMN inspection_damages.brand_id IS 'Marca del catálogo (FK a content_good_brands). Nullable para compatibilidad con datos existentes.';

-- ═══════════════════════════════════════════════════════════════
-- SEED DE DATOS
-- ═══════════════════════════════════════════════════════════════

-- Renombramientos de tipos existentes (UPDATE, no toca datos)
UPDATE content_good_types SET name = 'Maquinaria y Herramientas', description = 'Maquinaria industrial, herramientas eléctricas y manuales, equipos de trabajo.' WHERE name = 'Maquinaria';
UPDATE content_good_types SET name = 'Enseres de Cocina', description = 'Vajilla, cubiertos, ollas, sartenes, vasos, copas, termos, coolers. Bienes de uso durable de cocina (no consumibles).' WHERE name = 'Enseres Generales';
UPDATE content_good_types SET name = 'Computación y Móviles', description = 'Informática y móviles: notebooks, PC desktop, all-in-one, tablets, smartphones, smartwatches, monitores, routers, discos externos, auriculares, power banks, accesorios móvil.' WHERE name = 'Móviles';
UPDATE content_good_types SET name = 'Electrónica', description = 'Entretenimiento y audio/video: TV, consolas, equipos de sonido, parlantes, soundbars, proyectores, cámaras, drones. NO incluye computación ni móviles (ver Computación y Móviles).' WHERE name = 'Electrónica';
UPDATE content_good_types SET name = 'Joyas / Bisutería', description = 'Joyas, relojes tradicionales y bisutería de valor. NO incluye smartwatches (ver Computación y Móviles).' WHERE name = 'Joyas / Bisutería';

-- Tipos nuevos (INSERT, solo los que no existen)
INSERT INTO content_good_types (name, description) VALUES
  ('Alimentos / Víveres', 'Consumibles: vinos y licores de consumo, alimentos congelados, refrigerados, despensa no perecible. Caso típico: corte de luz que arruina freezers. Vino de guarda/inversión va a Arte/Colecciones.'),
  ('Jardinería / Exterior', 'Podadoras, motosierras, cortasetos, máquinas de césped, aspersores, muebles de jardín.'),
  ('Seguridad / Smart Home', 'Cámaras de seguridad, DVR/NVR, alarmas, cerraduras smart, timbres smart, sensores.'),
  ('Óptica / Astronomía', 'Telescopios, microscopios, binoculares, lupas, gafas/lentes recetados y de sol.')
ON CONFLICT DO NOTHING;

-- Brands (catálogo global)
INSERT INTO content_good_brands (name, country, is_active) VALUES
  ('Samsung', 'KR', true),
  ('LG', 'KR', true),
  ('Apple', 'US', true),
  ('Motorola', 'US', true),
  ('Xiaomi', 'CN', true),
  ('Huawei', 'CN', true),
  ('Honor', 'CN', true),
  ('Oppo', 'CN', true),
  ('Realme', 'CN', true),
  ('POCO', 'CN', true),
  ('Redmi', 'CN', true),
  ('Sony', 'JP', true),
  ('Panasonic', 'JP', true),
  ('Philips', 'NL', true),
  ('Whirlpool', 'US', true),
  ('Electrolux', 'SE', true),
  ('Bosch', 'DE', true),
  ('Siemens', 'DE', true),
  ('Midea', 'CN', true),
  ('Haier', 'CN', true),
  ('Hisense', 'CN', true),
  ('TCL', 'CN', true),
  ('Daewoo', 'KR', true),
  ('JVC', 'JP', true),
  ('Sharp', 'JP', true),
  ('Sanyo', 'JP', true),
  ('Hitachi', 'JP', true),
  ('Pioneer', 'JP', true),
  ('Kodak', 'US', true),
  ('Noblex', 'AR', true),
  ('BGH', 'AR', true),
  ('Admiral', 'US', true),
  ('AOC', 'TW', true),
  ('RCA', 'US', true),
  ('Telefunken', 'DE', true),
  ('Ken Brown', 'AR', true),
  ('Mademsa', 'CL', true),
  ('Fensa', 'CL', true),
  ('Klim', 'CL', true),
  ('CTI', 'CL', true),
  ('Generic', NULL, true),
  ('HP', 'US', true),
  ('Dell', 'US', true),
  ('Lenovo', 'CN', true),
  ('Acer', 'TW', true),
  ('Asus', 'TW', true),
  ('Microsoft', 'US', true),
  ('MSI', 'TW', true),
  ('Razer', 'US', true),
  ('Logitech', 'CH', true),
  ('Corsair', 'US', true),
  ('HyperX', 'US', true),
  ('Nintendo', 'JP', true),
  ('Xbox', 'US', true),
  ('Steam', 'US', true),
  ('Bose', 'US', true),
  ('JBL', 'US', true),
  ('Sonos', 'US', true),
  ('Marshall', 'SE', true),
  ('Beats', 'US', true),
  ('Sennheiser', 'DE', true),
  ('Audio-Technica', 'JP', true),
  ('Canon', 'JP', true),
  ('Nikon', 'JP', true),
  ('Fujifilm', 'JP', true),
  ('GoPro', 'US', true),
  ('DJI', 'CN', true),
  ('Epson', 'JP', true),
  ('Brother', 'JP', true),
  ('Xerox', 'US', true),
  ('Lexmark', 'US', true),
  ('Casio', 'JP', true),
  ('Texas Instruments', 'US', true),
  ('Fellowes', 'US', true),
  ('Rolex', 'CH', true),
  ('Cartier', 'FR', true),
  ('Omega', 'CH', true),
  ('Tag Heuer', 'CH', true),
  ('Breitling', 'CH', true),
  ('Patek Philippe', 'CH', true),
  ('Audemars Piguet', 'CH', true),
  ('Seiko', 'JP', true),
  ('Citizen', 'JP', true),
  ('Bulova', 'US', true),
  ('Tissot', 'CH', true),
  ('Swatch', 'CH', true),
  ('Daniel Wellington', 'SE', true),
  ('Tiffany & Co.', 'US', true),
  ('Bvlgari', 'IT', true),
  ('Pandora', 'DK', true),
  ('Swarovski', 'AT', true),
  ('Makita', 'JP', true),
  ('Bosch Professional', 'DE', true),
  ('DeWalt', 'US', true),
  ('Stanley', 'US', true),
  ('Black+Decker', 'US', true),
  ('Hilti', 'LI', true),
  ('Milwaukee', 'US', true),
  ('Metabo', 'DE', true),
  ('Truper', 'MX', true),
  ('Sodimac', 'CL', true),
  ('Bauker', 'CN', true),
  ('Einhell', 'DE', true),
  ('Toyota', 'JP', true),
  ('Hyundai', 'KR', true),
  ('Kia', 'KR', true),
  ('Chevrolet', 'US', true),
  ('Ford', 'US', true),
  ('Nissan', 'JP', true),
  ('Mazda', 'JP', true),
  ('Suzuki', 'JP', true),
  ('Honda', 'JP', true),
  ('Yamaha', 'JP', true),
  ('Bajaj', 'IN', true),
  ('Trek', 'US', true),
  ('Specialized', 'US', true),
  ('Giant', 'TW', true),
  ('Scott', 'CH', true),
  ('Bianchi', 'IT', true),
  ('Oxford', 'US', true),
  ('Mercurio', 'CL', true),
  ('Bicicletas Oxford', 'CL', true),
  ('Dico', 'CL', true),
  ('René Müller', 'CL', true),
  ('Mixo', 'CL', true),
  ('Dasec', 'CL', true),
  ('Diforco', 'CL', true),
  ('Dcorativa', 'CL', true),
  ('Rosen', 'CL', true),
  ('Cinzano', 'CL', true),
  ('Tottus Muebles', 'CL', true),
  ('IKEA', 'SE', true),
  ('Sodimac Muebles', 'CL', true),
  ('Derco Muebles', 'CL', true),
  ('Nike', 'US', true),
  ('Adidas', 'DE', true),
  ('Puma', 'DE', true),
  ('Under Armour', 'US', true),
  ('Reebok', 'US', true),
  ('Wilson', 'US', true),
  ('Head', 'AT', true),
  ('Babolat', 'FR', true),
  ('Speedo', 'US', true),
  ('Shimano', 'JP', true),
  ('Life Fitness', 'US', true),
  ('Bowflex', 'US', true),
  ('ProForm', 'US', true),
  ('Reebok Fitness', 'US', true),
  ('Olmo', 'AR', true),
  ('BH Fitness', 'ES', true),
  ('Fender', 'US', true),
  ('Gibson', 'US', true),
  ('Taylor', 'US', true),
  ('Martin', 'US', true),
  ('Ibanez', 'JP', true),
  ('Yamaha Music', 'JP', true),
  ('Roland', 'JP', true),
  ('Korg', 'JP', true),
  ('Casio Music', 'JP', true),
  ('Steinway', 'DE', true),
  ('Pearl', 'JP', true),
  ('Zildjian', 'US', true),
  ('Shure', 'US', true),
  ('Sennheiser Music', 'DE', true),
  ('Marshall Amplification', 'GB', true),
  ('Boss', 'JP', true),
  ('Invacare', 'US', true),
  ('Drive Medical', 'US', true),
  ('Karman', 'TW', true),
  ('Hofmann', 'CL', true),
  ('Omron', 'JP', true),
  ('Accu-Chek', 'DE', true),
  ('OneTouch', 'US', true),
  ('Philips Healthcare', 'NL', true),
  ('Zara', 'ES', true),
  ('H&M', 'SE', true),
  ('Uniqlo', 'JP', true),
  ('Corona', 'CL', true),
  ('Falabella', 'CL', true),
  ('Paris', 'CL', true),
  ('Ralph Lauren', 'US', true),
  ('Tommy Hilfiger', 'US', true),
  ('Calvin Klein', 'US', true),
  ('Levi''s', 'US', true),
  ('Nike Apparel', 'US', true),
  ('Adidas Apparel', 'DE', true),
  ('The North Face', 'US', true),
  ('Columbia', 'US', true),
  ('Doite', 'CL', true),
  ('Pyrex', 'US', true),
  ('Tupperware', 'US', true),
  ('Royal Doulton', 'GB', true),
  ('Luminarc', 'FR', true),
  ('Arcoroc', 'FR', true),
  ('Thermos', 'JP', true),
  ('Stanley', 'US', true),
  ('Igloo', 'US', true),
  ('Coleman', 'US', true),
  ('Oster', 'US', true),
  ('Moulinex', 'FR', true),
  ('Tefal', 'FR', true),
  ('Krups', 'DE', true),
  ('DeLonghi', 'IT', true),
  ('Nespresso', 'CH', true),
  ('Keurig', 'US', true),
  ('Breville', 'AU', true),
  ('Hamilton Beach', 'US', true),
  ('Imusa', 'CO', true),
  ('Rosen Cocina', 'CL', true),
  ('Singer', 'US', true),
  ('TP-Link', 'CN', true),
  ('Seagate', 'US', true),
  ('Western Digital', 'US', true),
  ('Garmin', 'US', true),
  ('Simmonds', 'CL', true),
  ('Valve', 'US', true),
  ('Fitbit', 'US', true),
  ('Withings', 'FR', true),
  ('Schwinn', 'US', true),
  ('Caloi', 'BR', true),
  ('Cannondale', 'US', true),
  ('Cervélo', 'CA', true),
  ('Pinarello', 'IT', true),
  ('Colnago', 'IT', true),
  ('Orbea', 'ES', true),
  ('BH Bicicletas', 'ES', true),
  ('Santa Cruz', 'US', true),
  ('Yeti Cycles', 'US', true),
  ('Ibis', 'US', true),
  ('Merida', 'TW', true),
  ('Kona', 'US', true),
  ('Norco', 'CA', true),
  ('Cube', 'DE', true),
  ('Focus', 'DE', true),
  ('Lapierre', 'FR', true),
  ('Volkswagen', 'DE', true),
  ('Mercedes-Benz', 'DE', true),
  ('BMW', 'DE', true),
  ('Audi', 'DE', true),
  ('Peugeot', 'FR', true),
  ('Renault', 'FR', true),
  ('Citroën', 'FR', true),
  ('Fiat', 'IT', true),
  ('Subaru', 'JP', true),
  ('Mitsubishi', 'JP', true),
  ('Great Wall', 'CN', true),
  ('Chery', 'CN', true),
  ('MG Motor', 'GB', true),
  ('Jac', 'CN', true),
  ('KTM', 'AT', true),
  ('Harley-Davidson', 'US', true),
  ('Ducati', 'IT', true),
  ('Kawasaki', 'JP', true),
  ('Vespa', 'IT', true),
  ('Piaggio', 'IT', true),
  ('Aprilia', 'IT', true),
  ('Hero', 'IN', true),
  ('TVS', 'IN', true),
  ('Royal Enfield', 'IN', true),
  ('Concha y Toro', 'CL', true),
  ('Santa Rita', 'CL', true),
  ('Casillero del Diablo', 'CL', true),
  ('Undurraga', 'CL', true),
  ('Santa Carolina', 'CL', true),
  ('Montes', 'CL', true),
  ('Errázuriz', 'CL', true),
  ('Viña Tarapacá', 'CL', true),
  ('San Pedro', 'CL', true),
  ('Cousiño Macul', 'CL', true),
  ('Don Melchor', 'CL', true),
  ('Almaviva', 'CL', true),
  ('Vik', 'CL', true),
  ('Pisco Capel', 'CL', true),
  ('Pisco Control', 'CL', true),
  ('Mistral', 'CL', true),
  ('Johnnie Walker', 'GB', true),
  ('Chivas Regal', 'GB', true),
  ('Jack Daniel''s', 'US', true),
  ('Buchanan''s', 'GB', true),
  ('Smirnoff', 'US', true),
  ('Absolut', 'SE', true),
  ('Beefeater', 'GB', true),
  ('Tanqueray', 'GB', true),
  ('Havana Club', 'CU', true),
  ('Ron Pampero', 'VE', true),
  ('Moët & Chandon', 'FR', true),
  ('Veuve Clicquot', 'FR', true),
  ('Codorníu', 'ES', true),
  ('Cristal', 'FR', true),
  ('Cerveza Kunstmann', 'CL', true),
  ('Cerveza Cristal', 'CL', true),
  ('Cerveza Becker', 'CL', true),
  ('Cerveza Royal Guard', 'CL', true),
  ('Heineken', 'NL', true),
  ('Corona', 'MX', true),
  ('Stella Artois', 'BE', true),
  ('Stihl', 'DE', true),
  ('Husqvarna', 'SE', true),
  ('Toro', 'US', true),
  ('Gardena', 'DE', true),
  ('McCulloch', 'US', true),
  ('Ryobi', 'JP', true),
  ('Hikvision', 'CN', true),
  ('Dahua', 'CN', true),
  ('Ring', 'US', true),
  ('Arlo', 'US', true),
  ('Google Nest', 'US', true),
  ('EZVIZ', 'CN', true),
  ('Reolink', 'CN', true),
  ('Swann', 'AU', true),
  ('Yale', 'US', true),
  ('Schlage', 'US', true),
  ('August', 'US', true),
  ('Lorex', 'CA', true),
  ('Celestron', 'US', true),
  ('Meade', 'US', true),
  ('Orion', 'US', true),
  ('Bushnell', 'US', true),
  ('Leica', 'DE', true),
  ('Zeiss', 'DE', true),
  ('Swarovski Optik', 'AT', true),
  ('Olympus', 'JP', true),
  ('Essilor', 'FR', true),
  ('Ray-Ban', 'US', true),
  ('Oakley', 'US', true),
  ('Persol', 'IT', true),
  ('Maui Jim', 'US', true)
ON CONFLICT DO NOTHING;

-- Products (con FK a content_good_types por nombre)
INSERT INTO content_good_products (content_good_type_id, name, description, sort_order, is_active)
VALUES
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Refrigerador', 'Refrigerador / heladera', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Congelador', 'Freezer / congelador horizontal o vertical', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Lavadora', 'Lavadora / lavarropas automático o semiautomático', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Secadora', 'Secadora de ropa', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Lavavajillas', 'Lavavajillas / dishwasher', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Cocina', 'Cocina a gas / eléctrica', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Horno', 'Horno empotrable o de piso', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Encimera', 'Encimera / placa de cocción', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Campana', 'Campana extractora', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Microondas', 'Horno microondas', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Estufa', 'Estufa a gas / parafina / eléctrica / pellet', 11, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Calefont', 'Calefont / calentador de agua', 12, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Termo', 'Termo / caldera de agua', 13, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Purificador de Agua', 'Purificador / dispensador de agua', 14, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Aire Acondicionado', 'Aire acondicionado split / portátil / ventana', 15, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Ventilador', 'Ventilador de pie / techo / mesa', 16, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Calefactor', 'Calefactor eléctrico / radiador', 17, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Plancha', 'Plancha de ropa', 18, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Aspiradora', 'Aspiradora / robot aspirador', 19, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Tostadora', 'Tostadora de pan', 20, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Batidora', 'Batidora manual / de mano', 21, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Licuadora', 'Licuadora de vaso / de mano', 22, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Cafetera', 'Cafetera filtro / espresso / cápsula', 23, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Olla Arrocera', 'Olla arrocera eléctrica', 24, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Freidora de Aire', 'Freidora de aire / air fryer', 25, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Multiprocesadora', 'Multiprocesadora / procesador de alimentos', 26, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Exprimidor', 'Exprimidor / juguera de jugos', 27, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Sandwichera', 'Sandwichera / plancha de pan', 28, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Hervidor', 'Hervidor eléctrico / tetera eléctrica', 29, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Rallador', 'Rallador eléctrico', 30, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Amasadora', 'Amasadora / batidora planetaria', 31, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrodomésticos'), 'Máquina de Coser', 'Máquina de coser doméstica', 32, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Televisor', 'TV LED / OLED / QLED', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Consola', 'Consola de videojuegos', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Equipo de Audio', 'Equipo de sonido / minicomponente', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Parlante', 'Parlante Bluetooth / smart speaker', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Soundbar', 'Barra de sonido', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Proyector', 'Proyector / videoproyector', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Cámara Fotográfica', 'Cámara DSLR / mirrorless / compacta', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Cámara de Video', 'Cámara de video / videocámara', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Drone', 'Drone / cuadricóptero', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Electrónica'), 'Consola Portátil', 'Consola portátil (Steam Deck, Switch Lite, etc.)', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Notebook', 'Notebook / laptop', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'PC Desktop', 'Computador de escritorio', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'All-in-One', 'PC todo en uno', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Tablet', 'Tablet (todos los tamaños)', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Monitor', 'Monitor de PC', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Router', 'Router / modem Wi-Fi', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Disco Duro Externo', 'Disco duro / SSD externo', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Smartphone', 'Teléfono celular smartphone', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Smartwatch', 'Reloj inteligente / smartwatch', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Auriculares', 'Auriculares con cable / inalámbricos', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Power Bank', 'Batería externa / cargador portátil', 11, true),
  ((SELECT id FROM content_good_types WHERE name = 'Computación y Móviles'), 'Funda / Accesorio Móvil', 'Funda, mica, cargador, soporte para móvil', 12, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Sofá', 'Sofá / sillín / sillón', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Silla', 'Silla de living / comedor / oficina', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Mesa de Comedor', 'Mesa de comedor', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Mesa de Centro', 'Mesa de centro / ratona', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Escritorio', 'Escritorio / mesa de trabajo', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Cama', 'Cama / somier', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Colchón', 'Colchón', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Velador', 'Velador / mesa de noche', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Closet', 'Closet / placard / ropero', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Cómoda', 'Cómoda / tocador', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Mueble de Cocina', 'Mueble modular de cocina', 11, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Mueble de Baño', 'Mueble / vanitorio de baño', 12, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Librero', 'Librero / estantería / bibliorack', 13, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Rack de TV', 'Rack / mueble para TV', 14, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Silla Ergonómica', 'Silla ergonómica de oficina', 15, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Archivador', 'Archivador / locker metálico', 16, true),
  ((SELECT id FROM content_good_types WHERE name = 'Muebles'), 'Mesa de Reunión', 'Mesa de reuniones / directorio', 17, true),
  ((SELECT id FROM content_good_types WHERE name = 'Ropa / Vestuario'), 'Ropa Casual', 'Ropa casual / formal / deportiva', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Ropa / Vestuario'), 'Calzado', 'Zapatos / zapatillas / sandalias / botas', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Ropa / Vestuario'), 'Cartera / Bolso', 'Cartera / bolso / mochila de vestir', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Ropa / Vestuario'), 'Accesorios de Vestir', 'Bufandas, guantes, cinturones, gorros', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Ropa / Vestuario'), 'Abrigo', 'Abrigos / parkas / chaquetas / blazers', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Reloj', 'Reloj de pulsera / de bolsillo', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Anillo', 'Anillo / sortija', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Collar', 'Collar / gargantilla', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Aros', 'Aros / pendientes', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Pulsera', 'Pulsera / brazalete', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Cadena', 'Cadena de oro / plata', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Joyas / Bisutería'), 'Piercing', 'Piercing / arete', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Taladro', 'Taladro / atornillador eléctrico', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Amoladora', 'Amoladora / esmeril angular', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Soldadora', 'Soldadora eléctrica / inverter', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Compresor', 'Compresor de aire', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Generador', 'Generador eléctrico / grupo electrógeno', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Hidrolavadora', 'Hidrolavadora / hidrolavadora a presión', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Sierra Circular', 'Sierra circular / caladora / ingletadora', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Cortadora de Cerámica', 'Cortadora de cerámica / gres', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Lijadora', 'Lijadora orbital / de banda / roto-lijadora', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Maquinaria y Herramientas'), 'Caja de Herramientas', 'Caja / set de herramientas manuales', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Automóvil', 'Automóvil / auto particular', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Camioneta', 'Camioneta / SUV', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Motocicleta', 'Motocicleta / moto', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Bicicleta', 'Bicicleta tradicional / urbana', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Bicicleta Eléctrica', 'Bicicleta eléctrica / e-bike', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Scooter Eléctrico', 'Scooter / patinete eléctrico', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Vehículos'), 'Furgón', 'Furgón / van / vehículo comercial', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Impresora', 'Impresora láser / inyección', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Multifuncional', 'Impresora multifuncional / todo en uno', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Escáner', 'Escáner de documentos', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Shredder', 'Destructor / trituradora de papel', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Calculadora', 'Calculadora de escritorio / científica', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Pizarrón', 'Pizarrón / whiteboard', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Oficina'), 'Fax', 'Fax / telefax', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Cinta de Correr', 'Cinta / treadmill de correr', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Bicicleta Estática', 'Bicicleta estática / spinning', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Elíptica', 'Elíptica / cross trainer', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Mancuernas', 'Mancuernas / pesas / discos', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Banco de Pesas', 'Banco / multistación de pesas', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Raqueta', 'Raqueta de tenis / pádel / bádminton', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Pelota', 'Pelota de fútbol / básquet / vóleibol', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Tabla de Surf', 'Tabla de surf / bodyboard', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Tabla de Paddle', 'Tabla de paddle surf / SUP', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Esquí', 'Esquí / snowboard + fijaciones + botas', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Casco Deportivo', 'Casco de bici / moto / ski', 11, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Deportivo'), 'Guantes Deportivos', 'Guantes de boxeo / ciclismo / ski', 12, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Guitarra', 'Guitarra eléctrica / acústica / clásica', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Bajo', 'Bajo eléctrico / acústico', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Piano', 'Piano de cola / vertical / digital', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Teclado', 'Teclado / sintetizador / workstation', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Batería', 'Batería acústica / electrónica', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Violín', 'Violín / viola / violonchelo', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Saxofón', 'Saxofón alto / tenor', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Flauta', 'Flauta traversa / dulce', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Ukelele', 'Ukelele soprano / concierto / tenor', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Micrófono', 'Micrófono vocal / instrumento', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Instrumentos Musicales'), 'Amplificador', 'Amplificador de guitarra / bajo', 11, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Cuadro / Pintura', 'Cuadro / pintura original', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Escultura', 'Escultura / estatua', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Moneda de Colección', 'Moneda antigua / de colección', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Filatelia', 'Estampillas / sellos de colección', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Vino de Colección', 'Vino de guarda / colección', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Libro Antiguo', 'Libro antiguo / primera edición', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Arte / Colecciones'), 'Alfombra de Colección', 'Alfombra persa / oriental de valor', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Libros / Documentos'), 'Libro', 'Libro / libro técnico / libro universitario', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Libros / Documentos'), 'Enciclopedia', 'Enciclopedia / colección completa', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Libros / Documentos'), 'Cómics / Manga', 'Cómics / manga / graphic novel', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Libros / Documentos'), 'Documento Importante', 'Documento legal / escritura / título', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Silla de Ruedas', 'Silla de ruedas manual / eléctrica', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Andador', 'Andador / muletas / bastón', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Cama Clínica', 'Cama clínica / hospitalaria', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Concentrador de Oxígeno', 'Concentrador / balón de oxígeno', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Medidor de Presión', 'Tensiómetro / baumanómetro', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Glucómetro', 'Glucómetro / medidor de glicemia', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Equipamiento Médico'), 'Botiquín', 'Botiquín / kit de primeros auxilios', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Vajilla', 'Set de vajilla / platos / bowls', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Cubiertos', 'Set de cubiertos', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Ollas', 'Set de ollas / batería de cocina', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Sartenes', 'Set de sartenes', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Vasos / Copas', 'Set de vasos / copas', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Set de Té / Café', 'Tetera / taza / set de té', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Termo', 'Termo / vacuna / mate', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Enseres de Cocina'), 'Cooler / Hielera', 'Cooler / hielera / conservadora', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Otros'), 'Otro', 'Bien no clasificado en las categorías anteriores', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Vino Tinto', 'Vino tinto de consumo (no colección)', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Vino Blanco', 'Vino blanco de consumo', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Vino Espumoso / Champagne', 'Espumosos, champagne, cava', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Pisco', 'Pisco chileno', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Whisky / Destilado', 'Whisky, vodka, ron, gin, tequila, pisco premium', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Cerveza', 'Cerveza de consumo (no colección)', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Alimentos Congelados', 'Carne, pescado, preparados congelados — caso corte de luz', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Alimentos Refrigerados', 'Lácteos, frescos, refrigerados', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Despensa / No Perecibles', 'Enlatados, secos, harinas, aceites, conservas', 9, true),
  ((SELECT id FROM content_good_types WHERE name = 'Alimentos / Víveres'), 'Aceite / Vinagre', 'Aceites de cocina, vinagres, aderezos de valor', 10, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Podadora de Césped', 'Cortacésped eléctrico / a bencina / manual', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Motosierra', 'Motosierra / sierra de cadena', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Sopladora / Aspiradora', 'Sopladora de hojas / aspiradora de jardín', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Cortasetos', 'Cortasetos eléctrico / a bencina', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Herramientas de Jardín', 'Palas, rastrillos, tijeras de podar, horquetas', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Aspersor / Riego', 'Sistema de riego, aspersores, mangueras', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Carretilla', 'Carretilla / carretón de jardín', 7, true),
  ((SELECT id FROM content_good_types WHERE name = 'Jardinería / Exterior'), 'Mueble de Jardín', 'Muebles de exterior, hamacas, pérgolas', 8, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'Cámara de Seguridad', 'Cámara IP / CCTV / dome / bullet', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'DVR / NVR', 'Grabador de video de vigilancia', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'Alarma', 'Panel de alarma / kit de alarma', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'Cerradura Smart', 'Cerradura electrónica / smart lock', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'Timbre Smart', 'Timbre con video / video doorbell', 5, true),
  ((SELECT id FROM content_good_types WHERE name = 'Seguridad / Smart Home'), 'Sensor de Movimiento', 'Sensores PIR, detectores, kit sensores', 6, true),
  ((SELECT id FROM content_good_types WHERE name = 'Óptica / Astronomía'), 'Telescopio', 'Telescopio refractor / reflector / catadióptrico', 1, true),
  ((SELECT id FROM content_good_types WHERE name = 'Óptica / Astronomía'), 'Microscopio', 'Microscopio óptico / estereoscópico / digital', 2, true),
  ((SELECT id FROM content_good_types WHERE name = 'Óptica / Astronomía'), 'Binoculares', 'Prismáticos / binoculares', 3, true),
  ((SELECT id FROM content_good_types WHERE name = 'Óptica / Astronomía'), 'Gafas / Lentes', 'Lentes recetados / lentes de sol', 4, true),
  ((SELECT id FROM content_good_types WHERE name = 'Óptica / Astronomía'), 'Lupa', 'Lupa / lente de aumento', 5, true)
ON CONFLICT DO NOTHING;
